### ISSUE TITLE
Undefined constant "App\Providers\LC_MESSAGES"

### ISSUE THREAD

**Issue by eduardr10** [eusonlito/crypto#9]
Traté borrándola, comentándola, añadiendo una variable con ese nombre en .env, pero no he conseguido solucionarlo.

Uso windows 10
php 8.3.1 (También probé con 8.2.8)
SQLite

![image](https://github.com/eusonlito/crypto/assets/56480067/854aa952-ab44-4780-b417-42911e2ce60e)

**Comment by eusonlito** [comment]
Necesitas instalar la extensión de PHP `php8.3-intl`.

**Comment by eusonlito** [comment]
Solucionado?

**Comment by eduardr10** [comment]
Hola, Lito. Aún no he tenido oportunidad de volver a intentarlo. Lo que sí pude ver es que, según Laragon, tengo activada la extensión intl, pero como digo, no he tenido otra oportunidad de probar.

**Comment by eusonlito** [comment]
Okey! en caso de que esté activa deberías poder acceder a esta constante, según la documentación de [PHP](https://www.php.net/manual/en/function.setlocale.php):

> [LC_MESSAGES](https://www.php.net/manual/en/string.constants.php#constant.lc-messages) for system responses (available if PHP was compiled with libintl)
